using System.Text;
using Coral.Core.Models;

namespace Coral.Core.Generators;

/// <summary>
/// Port of <c>StrategyForge/Generators/ClaudeMdGenerator.swift</c>. Generates /
/// updates the repo-root CLAUDE.md. Coral-owned content lives inside a marked
/// section so an existing CLAUDE.md is never clobbered — only the delimited block
/// is inserted or replaced (idempotent).
/// </summary>
public static class ClaudeMdGenerator
{
    public const string StartMarker = "<!-- CORAL:START -->";
    public const string EndMarker = "<!-- CORAL:END -->";
    /// <summary>Legacy markers from the app's former name. Still recognized when
    /// merging so an already-generated CLAUDE.md gets its block replaced (and
    /// upgraded to the new markers) instead of appending a duplicate.</summary>
    public const string LegacyStartMarker = "<!-- STRATEGYFORGE:START -->";
    public const string LegacyEndMarker = "<!-- STRATEGYFORGE:END -->";
    public const string FileName = "CLAUDE.md";

    /// <summary>Break any Coral marker that appears inside user-authored content,
    /// so a name/description containing <c>&lt;!-- CORAL:END --&gt;</c> can't
    /// prematurely close the managed block and corrupt the next merge.</summary>
    public static string NeutralizeMarkers(string s) => s
        .Replace(StartMarker, "<!-- coral start -->")
        .Replace(EndMarker, "<!-- coral end -->")
        .Replace(LegacyStartMarker, "<!-- sf start -->")
        .Replace(LegacyEndMarker, "<!-- sf end -->");

    /// <summary>The Coral-managed section (WITHOUT the markers). Regenerated on
    /// every write. <paramref name="memory"/> is an optional, pre-rendered
    /// "Learnings from past runs" block (MemoryDigest, not ported yet); empty
    /// (the default) keeps output byte-identical to before it existed.</summary>
    public static string Section(Strategy strategy, string binary = "claude", string memory = "")
    {
        var orchestrator = strategy.Orchestrator;
        var orchestratorName = orchestrator?.Name ?? "orchestrator";
        var orchestratorModel = orchestrator is null ? "—" : orchestrator.Model.DisplayName();
        var orchestratorModelId = orchestrator is null ? "—" : orchestrator.Model.ToRawValue();

        var sb = new StringBuilder();
        sb.Append($"# Multi-agent strategy: {strategy.Name}\n\n");
        sb.Append($"{strategy.Description}\n\n");
        sb.Append("> Generated by Coral. This section is managed automatically; ");
        sb.Append("edit outside the markers to keep your changes.\n\n");

        sb.Append("## Orchestrator\n\n");
        sb.Append($"The orchestrator is the **main Claude Code session** (`{orchestratorName}`). ");
        sb.Append("Its model is **not** set in a file — it is chosen at launch.\n\n");
        sb.Append($"- Suggested model: **{orchestratorModel}** (`{orchestratorModelId}`)\n\n");
        sb.Append(LaunchCommandGenerator.Instructions(strategy, binary)).Append("\n\n");

        sb.Append("## How to orchestrate\n\n");
        sb.Append($"{strategy.OrchestrationNotes}\n\n");

        if (strategy.Skills.Count > 0)
        {
            sb.Append("## Available skills\n\n");
            sb.Append("These Agent Skills live in `.claude/skills/` and are pulled into context ");
            sb.Append("automatically when a task matches. Use them instead of improvising:\n\n");
            foreach (var slug in strategy.Skills)
            {
                sb.Append($"- `{slug}` — see `.claude/skills/{slug}/SKILL.md`.\n");
            }
            sb.Append('\n');
        }

        var subagents = strategy.SubagentRoles;
        if (subagents.Count == 0)
        {
            sb.Append("## Subagents\n\n");
            sb.Append("_None — this is a solo configuration with no delegation._\n\n");
        }
        else
        {
            sb.Append("## Available subagents\n\n");
            sb.Append("| Subagent | Role | Model | When to use |\n");
            sb.Append("|---|---|---|---|\n");
            var subagentTypes = new List<string>();
            foreach (var role in subagents)
            {
                var count = Math.Max(role.Count, 1);
                string nameCell;
                if (count == 1)
                {
                    nameCell = $"`{role.Name}`";
                    subagentTypes.Add(role.Name);
                }
                else
                {
                    nameCell = $"`{role.Name}-1`…`{role.Name}-{count}`";
                    subagentTypes.AddRange(Enumerable.Range(1, count).Select(i => $"{role.Name}-{i}"));
                }
                var when = role.Description.Replace("\n", " ").Replace("|", "\\|");
                sb.Append($"| {nameCell} | {role.Role.DisplayName()} | {role.Model.DisplayName()} | {when} |\n");
            }
            sb.Append('\n');

            // The delegation is the whole point — and the model will NOT delegate
            // unless told to use the Task tool explicitly. Make it a hard rule and
            // name the exact `subagent_type` values it may call.
            var names = string.Join(", ", subagentTypes.Select(t => $"`{t}`"));
            sb.Append("## Delegate with the Task tool (required)\n\n");
            sb.Append("You are the orchestrator. **Do the work by DELEGATING, not by doing it all yourself.** ");
            sb.Append("For anything that fits a subagent above, you MUST call the **Task tool**:\n\n");
            sb.Append($"```\nTask(subagent_type: \"{(subagentTypes.Count > 0 ? subagentTypes[0] : "worker")}\", ");
            sb.Append("description: \"a precise, self-contained brief with scope + acceptance criteria\")\n```\n\n");
            sb.Append($"- Available `subagent_type` values: {names}.\n");
            sb.Append("- When work is parallelizable, launch several subagents **in the same turn** ");
            sb.Append("(multiple Task calls at once) so they run concurrently.\n");
            sb.Append("- Give each a complete brief — subagents can't see the conversation, each other, ");
            sb.Append("or delegate further.\n");
            sb.Append("- Then collect their reports, integrate, resolve conflicts, and verify.\n");
            sb.Append("- Only skip delegation for trivial one-line answers that need no real work.\n\n");

            sb.Append(DelegationPlaybook).Append('\n');
        }

        // Working agreement — Anthropic's tested prompt guidance for Fable 5.
        sb.Append(WorkingAgreement).Append('\n');

        // Learnings from past runs (cross-project memory), when any apply.
        var mem = memory.Trim();
        if (mem.Length > 0) sb.Append(mem).Append("\n\n");

        sb.Append("## Limitations (Claude Code)\n\n");
        sb.Append("- **Single level of delegation.** The orchestrator delegates to ");
        sb.Append("subagents; subagents cannot delegate further.\n");
        sb.Append("- **No lateral communication.** Subagents do not talk to each other; ");
        sb.Append("they only report back to the orchestrator.\n");
        sb.Append("- **Orchestrator model is a launch setting**, documented above — not ");
        sb.Append("agent frontmatter.\n");

        // The section is wrapped in CORAL:START/END markers by the merge; make sure
        // the body can never contain a real marker (injected via name/description/notes).
        return NeutralizeMarkers(sb.ToString());
    }

    /// <summary>How to delegate *well* — not just that you must. Makes the
    /// orchestrator hand work off like a manager with a capable engineer, not a
    /// micromanager with an intern.</summary>
    public const string DelegationPlaybook =
        "## Delegate like a manager, not a micromanager\n" +
        "\n" +
        "The lead's job is judgment — what to build, what to constrain, who writes it —\n" +
        "not typing the implementation. These habits keep the expensive lead cheap:\n" +
        "\n" +
        "- **Delegate early, not late.** Hand off after a few reconnaissance actions, " +
        "*before* you pull the important files into your own context and make the design " +
        "decisions yourself. A late handoff for only the mechanical tail wastes the lead " +
        "on the expensive work. In practice the lead often never needs to edit code at all.\n" +
        "- **Brief with constraints, not keystrokes.** Write a spec-quality handoff: " +
        "enumerate the constraints, edge cases, and an explicit definition of \"done\" " +
        "(e.g. \"`operator()` must be O(1) in pointer length — NO full token scan\"). A " +
        "constraint you write down can't be forgotten mid-implementation; dictating the " +
        "implementation line by line can. Specify outcomes, let the subagent choose the how.\n" +
        "- **Review the diff; don't rewrite it.** When work comes back, a cheap " +
        "`git diff` / `git show` is usually enough. If you find a bug, prefer another " +
        "small handoff over pulling the files back and fixing them yourself at lead " +
        "prices — distrust doesn't increase correctness, it just moves cost up-tier.\n" +
        "- **Know what NOT to delegate.** Short tasks with nothing between deciding and " +
        "shipping, and serial debugging where the accumulated context *is* the work, " +
        "don't decompose — do those yourself. Good delegation is a judgment call, not a " +
        "quota: the same judgment that writes a good brief also knows when not to write one.\n" +
        "\n";

    /// <summary>Anthropic's tested prompt guidelines for Fable 5, applied repo-wide.</summary>
    public const string WorkingAgreement =
        "## Working agreement (Fable 5 best practices)\n" +
        "\n" +
        "Applies to every agent in this repo.\n" +
        "\n" +
        "- **Scope discipline — no gold-plating.** Don't add features, refactor, or " +
        "introduce abstractions beyond what the task requires. A bug fix doesn't need " +
        "surrounding cleanup. Don't design for hypothetical future requirements: do the " +
        "simplest thing that works well. Only validate at system boundaries.\n" +
        "- **Act, don't over-plan.** When you have enough information to act, act. Don't " +
        "re-derive established facts, re-litigate settled decisions, or narrate options " +
        "you won't pursue — give a recommendation, not a survey.\n" +
        "- **Grounded progress.** Before reporting progress, audit each claim against a " +
        "tool result from this session. Only report work you can point to evidence for. " +
        "If tests fail, say so with the output; if a step was skipped, say that.\n" +
        "- **Verification beats self-critique.** A fresh-context subagent that saw " +
        "neither the plan nor the draft verifies the result against the spec. \"Done\" " +
        "means a check passed — not that the author is confident.\n" +
        "- **Never echo internal reasoning** in the response text (it triggers Fable 5's " +
        "reasoning-extraction safeguard); rely on the structured thinking instead.\n" +
        "- **Memory.** One lesson per file with a one-line summary; record corrections " +
        "and confirmed approaches with why they mattered; update existing notes instead " +
        "of duplicating, and delete notes that turn out to be wrong.\n" +
        "\n";

    /// <summary>The full managed block, including the start/end markers.</summary>
    public static string MarkedBlock(Strategy strategy, string binary = "claude", string memory = "") =>
        $"{StartMarker}\n{Section(strategy, binary, memory)}{EndMarker}\n";

    // MARK: - Idempotent merge

    /// <summary>Merge the managed block into an existing CLAUDE.md.
    /// <list type="bullet">
    /// <item>If <paramref name="existing"/> is null/empty → returns just the managed block.</item>
    /// <item>If it already contains the markers → replaces everything between them.</item>
    /// <item>Otherwise → appends the managed block, preserving prior content.</item>
    /// </list>
    /// Running this repeatedly with the same strategy is idempotent.</summary>
    public static string Merged(string? existing, Strategy strategy, string binary = "claude", string memory = "")
    {
        var block = MarkedBlock(strategy, binary, memory);

        if (string.IsNullOrEmpty(existing))
        {
            return block;
        }

        var range = MarkedRange(existing);
        if (range is { } r)
        {
            var trimmedBlock = block.Trim('\n');
            return existing[..r.Start] + trimmedBlock + existing[r.End..];
        }

        // Append, ensuring a blank line separator. Any stray marker left behind (a
        // START whose END was deleted by hand or eaten by a merge conflict) is
        // neutralized first: otherwise the NEXT merge would pair the stray START
        // with the appended block's END and wipe the user's content in between.
        var baseText = existing;
        foreach (var marker in new[] { StartMarker, EndMarker, LegacyStartMarker, LegacyEndMarker })
        {
            if (baseText.Contains(marker, StringComparison.Ordinal))
            {
                baseText = baseText.Replace(marker, marker.Replace(" -->", " (stray) -->"));
            }
        }
        var separator = baseText.EndsWith('\n') ? "\n" : "\n\n";
        return baseText + separator + block;
    }

    /// <summary>The range covering the marked block (inclusive of both markers), or
    /// null. Recognizes the current markers first, then the legacy ones. The end
    /// marker is searched ONLY after the start, so disordered/duplicated markers
    /// (end before start) yield null (→ safe append) instead of a bad range.</summary>
    public static (int Start, int End)? MarkedRange(string text) =>
        FindRange(text, StartMarker, EndMarker) ?? FindRange(text, LegacyStartMarker, LegacyEndMarker);

    private static (int Start, int End)? FindRange(string text, string startMk, string endMk)
    {
        var start = text.IndexOf(startMk, StringComparison.Ordinal);
        if (start < 0) return null;
        var end = text.IndexOf(endMk, start + startMk.Length, StringComparison.Ordinal);
        if (end < 0) return null;
        return (start, end + endMk.Length);
    }
}
