using System.Globalization;
using Coral.Core.Models;
using Coral.Core.Services;
using Coral.Core.ViewModels;

namespace Coral.Core.Generators;

/// <summary>
/// Port of <c>StrategyForge/Generators/MissionReport.swift</c>. Assembles a
/// shareable "mission report" from a finished run using data the app already
/// tracks (the activity timeline, tokens, cost, the team). The headline — "my
/// 4-agent team did X for $0.83" — is the shareable hook of the discovery phase.
/// Pure and testable; the view just renders + exports what this produces.
/// </summary>
public static class MissionReport
{
    /// <summary>Per-agent summary line for the report table.</summary>
    public sealed record AgentLine(string Name, string Role, string Model, int Steps, string Span);

    /// <summary>A one-line, shareable headline: "A 4-agent team finished for $0.83."</summary>
    public static string Headline(int agentCount, double costUsd, int tokens)
    {
        var cost = costUsd > 0 ? $"${costUsd.ToString("F2", CultureInfo.InvariantCulture)}" : $"{FormatTokens(tokens)} tokens";
        if (agentCount <= 1) return $"A single agent finished for {cost}.";
        return $"A {agentCount}-agent team finished for {cost}.";
    }

    /// <summary>Derive per-agent lines from the strategy + the run's timeline
    /// (orchestrator owns the un-delegated steps; subagents match loosely by
    /// name via <see cref="AgentNameMatcher"/>).</summary>
    public static List<AgentLine> AgentLines(Strategy strategy, IReadOnlyList<ActivityStep> timeline)
    {
        (int Count, string Span) Stats(Func<ActivityStep, bool> predicate)
        {
            var steps = timeline.Where(s => !s.IsDelegation && predicate(s)).ToList();
            if (steps.Count == 0) return (0, "");
            var first = steps[0].At;
            var last = steps[^1].At;
            var span = (last - first).TotalSeconds >= 1 ? ActivityElapsed(first, last) : "";
            return (steps.Count, span);
        }

        var lines = new List<AgentLine>();
        var orchestrator = strategy.Orchestrator;
        if (orchestrator is not null)
        {
            var (n, span) = Stats(s => s.Agent is null);
            lines.Add(new AgentLine(TitleCase(orchestrator.Name), orchestrator.Role.DisplayName(),
                orchestrator.ModelDisplayName, n, span));
        }
        foreach (var role in strategy.SubagentRoles)
        {
            var name = TitleCase(role.Name);
            var (n, span) = Stats(s => AgentNameMatcher.TitlesMatch(s.Agent ?? "", name));
            lines.Add(new AgentLine(name, role.Role.DisplayName(), role.ModelDisplayName, n, span));
        }
        return lines;
    }

    private static string TitleCase(string s)
    {
        var words = s.Replace('-', ' ').Split(' ', StringSplitOptions.RemoveEmptyEntries);
        return string.Join(' ', words.Select(w => char.ToUpperInvariant(w[0]) + w[1..]));
    }

    private static string ActivityElapsed(DateTimeOffset from, DateTimeOffset to)
    {
        var s = Math.Max(0, (int)(to - from).TotalSeconds);
        return s < 60 ? $"{s}s" : $"{s / 60}m {(s % 60).ToString("D2", CultureInfo.InvariantCulture)}s";
    }

    /// <summary>The full Markdown report.</summary>
    public static string Markdown(string title, string strategyName, List<AgentLine> agents,
        int tokens, double costUsd, string elapsed, string outcome)
    {
        var acted = agents.Where(a => a.Steps > 0).ToList();
        var count = Math.Max(acted.Count, agents.Count);
        var sb = new System.Text.StringBuilder();
        sb.Append("# Mission report — ").Append(title.Length == 0 ? strategyName : title).Append("\n\n");
        sb.Append("> ").Append(Headline(count, costUsd, tokens)).Append("\n\n");
        sb.Append("**Team:** ").Append(strategyName).Append(" · ").Append(agents.Count).Append(" agents  \n");
        sb.Append("**Cost:** ").Append(costUsd > 0 ? $"${costUsd.ToString("F2", CultureInfo.InvariantCulture)}" : "—").Append(" · ");
        sb.Append("**Tokens:** ").Append(FormatTokens(tokens));
        if (elapsed.Length > 0) sb.Append(" · **Time:** ").Append(elapsed);
        sb.Append("\n\n## Agents\n\n");
        sb.Append("| Agent | Role | Model | Steps | Time |\n| --- | --- | --- | ---: | ---: |\n");
        foreach (var a in agents)
        {
            sb.Append("| ").Append(a.Name).Append(" | ").Append(a.Role).Append(" | ").Append(a.Model)
              .Append(" | ").Append(a.Steps).Append(" | ").Append(a.Span.Length == 0 ? "—" : a.Span).Append(" |\n");
        }
        var trimmed = outcome.Trim();
        if (trimmed.Length > 0)
        {
            var capped = trimmed.Length > 1200 ? trimmed[..1200] + "…" : trimmed;
            sb.Append("\n## Outcome\n\n").Append(capped).Append('\n');
        }
        sb.Append("\n---\n*Generated by Coral.*\n");
        return sb.ToString();
    }

    private static string FormatTokens(int n)
    {
        if (n >= 1_000_000) return $"{(n / 1_000_000.0).ToString("F1", CultureInfo.InvariantCulture)}M";
        if (n >= 1_000) return $"{(n / 1_000.0).ToString("F1", CultureInfo.InvariantCulture)}k";
        return n.ToString();
    }
}
